version: '3.7'

services:
  mongodb:
    container_name: mongodb
    image: mongo:4.2
    restart: always
    hostname: mongodb
    environment:
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_ROOT_USERNAME: admin
    ports:
      - 27017:27017
